import Link from 'next/link';
import './global.css';

export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-amber-200 text-amber-900">
        <div className="container my-8">
          <div className="appGrid">
            <header className="border-r-4 border-r-amber-500">
              <nav className="flex">
                <ul>
                  <li><Link href="/offers" className="text-amber-900 hover:text-amber-700 py-2 block">offers</Link></li>
                  <li><Link href="/contracts" className="text-amber-900 hover:text-amber-700 py-2 block">contracts</Link></li>
                  <li><Link href="/settings" className="text-amber-900 hover:text-amber-700 py-2 block">account settings</Link></li>
                </ul>
              </nav>
            </header>
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
